### ISSUE TITLE
Static pages?

### ISSUE THREAD

**Issue by martensson** [vjeantet/hugo-theme-casper#11]
Hi @vjeantet 

Thanks a lot for porting this theme from Ghost to Hugo. I am a great fan of static pages, Go and the default Casper theme from Ghost, so it's a great combo.

I have made some tests to migrate my page but I stumbled into some issues. First of is the problem that I don't know how to create normal static pages that are not shown as normal posts? Is that possible? I tried to just generate a post directly inside the "content" folder but the CSS is wrong and the text is not centered.

It would be great to be able to create static pages that are not posts, like "about", etc.

Thanks a lot and keep up the good work! :+1:

Regards,
Benjamin

**Comment by vjeantet** [comment]
Hi Benjamin, I'll have a look on this issue

**Comment by martensson** [comment]
Thanks a lot @vjeantet !

**Comment by vjeantet** [comment]
Hello @martensson , i tried to reproduce the bug you describe, but my text is centered, can you send me an example .md file to put directly into ```content``` folder ?

**Comment by martensson** [comment]
Hi @vjeantet, thanks for coming back and sorry for the late answer. I actually retried again now and I can't seem to recreate it myself either.

And regarding the static pages a quick fix was to just add the following to the themes index.html:
`range $index, $page := (where .Paginator.Pages "Section" "post" )`
That way they are not shown in the normal posts list.

**Comment by vjeantet** [comment]
good catch, i will use your snippet
