### ISSUE TITLE
Hugo > 0.32.4 Layouts Issue

### ISSUE THREAD

**Issue by tarpdalton** [vjeantet/hugo-theme-casper#110]
I'm not sure if its only my environment/site, but building it with hugo >= 0.33 results in the home page not rendering correctly. I haven't had a change to look into it more, but I thought I would raise the issue for people upgrading their hugo versions.

I'll add more info as I test things out. Right now hugo 0.32.4 works fine.

The layout logic [changed](https://gohugo.io/news/0.33-relnotes/), so that is probably part of the issue.

**Comment by tarpdalton** [comment]
Ok it took me a little while but the problem is pretty simple. It had to do with the [template lookup order](https://gohugo.io/templates/lookup-order/). Hugo now looks in `layouts/page` before `layouts/index.html`.

So you simply have to move `layouts/index.html` to `/layouts/page/index.html`. That seemed to fix the problem.

**Comment by jorgegarciadev** [comment]
@tarpdalton Thank you.

**Comment by paskal** [comment]
It's fixed? Could it be closed?

**Comment by paskal** [comment]
Sorry for posting in the unrelated issue, I don't want to create new one for such insignificant event: I'm not sure github sent notifications to mentioned authors, so posting double there: @vjeantet, theme highlight is out, this very theme is in it, additional info on https://github.com/paskal/terrty/issues/1.
