### ISSUE TITLE
css class file names are not matching

### ISSUE THREAD

**Issue by varun06** [vjeantet/hugo-theme-casper#12]
Hey,

for content, you are getting the class name as `<article class = {{.Type}}>`. But it get the class name as 'posts' but css has class name as .post. So the posts are not formatted properly. I hardcoded for now, but something you can look into. I can PR if I get some time to look into it.

Thanks a lot for this theme.

**Comment by vjeantet** [comment]
Hi Varun, thanks and good catch !
Feel free to send your pr, you're wellcome.
