### ISSUE TITLE
confusing error in pagination, perhaps from inadequate setup

### ISSUE THREAD

**Issue by vielmetti** [vjeantet/hugo-theme-casper#22]
I just installed Hugo and I just installed Casper and I'm sort of bumbling around trying to find a theme to my liking, especially one that does pagination.

In setting up Casper I ran across this error in the log files. There are pagination pages created, but most of them have no content. (The first one works.)

Mostly trying to figure out what I did and how to fix....thanks for any help.

```
ERROR: 2015/07/14 Expecting to find a template in either the theme/layouts or /layouts in one of the following relative locations [post/post.html _default/post.html theme/post/post.html theme/_default/post.html]
ERROR: 2015/07/14 Unable to render [post/post.html _default/post.html theme/post/post.html theme/_default/post.html]
```

**Comment by monfresh** [comment]
@vielmetti I ran into this as well, and after doing some research, I realized that it's because this theme is not compatible with the latest version of Hugo (0.14 at this time). You can read more about the issue here: http://discuss.gohugo.io/t/most-themes-are-incompatible-with-hugo-0-12/565/6 and here: https://github.com/spf13/hugoThemes/issues/3

For now, you'll have to try other themes that are compatible, such as `hyde`, `angels-ladder`, and `redlounge`. You can see if a theme is compatible by running `hugo -t [name of theme]`. If it's compatible, it won't display any errors.

**Comment by vjeantet** [comment]
@monfresh Thanks for report i'll fix this today

**Comment by vjeantet** [comment]
@monfresh @vielmetti , i can not reproduce the error you mention.

I tried with a blank new site, with hugo 0.14 and hugo 0.15-DEV, no problem

Can you send/share your hugobasedir ? to explain how to reproduce ?

**Comment by vjeantet** [comment]
@vielmetti, i used the "tracker" repo, i got the error.

This is because on some content files, there is a ```layout: post``` and hugo is looking for a post templates which does not exists... if you remove ```layout: post``` on content files it will works.

**Comment by vjeantet** [comment]
I think there is a bug in Hugo itself, because [documentation](http://gohugo.io/templates/content/#single:05301946b75cb988bc2be8549079b4fa) states that if a layout's specific template is not found,  hugo will use ```/layouts/_default/single.html```.

**Comment by vjeantet** [comment]
issue opened in hugo repo https://github.com/spf13/hugo/issues/1306

**Comment by monfresh** [comment]
Ah, I see the issue now. I copied over my posts from my Octopress blog, and all of my posts had `layout: post` in the front matter. According to the Hugo documentation, `layout` isn't supported in the front matter. After I removed that line from all my posts, Casper worked fine.

**Comment by vielmetti** [comment]
Yes, I have `layout: post` in the front matter of a lot of posts copied in.

**Comment by vjeantet** [comment]
The issue is reported, and confirmed as a bug.

**Comment by vjeantet** [comment]
Casper theme updated, now even if you let the ```layout:post``` in the front matter of content files, it should works.

Let me know.

**Comment by vjeantet** [comment]
for information : Hugo has been fixed too in https://github.com/spf13/hugo/commit/43891e39947ee30d6667ad4f8154b8c3d93fdd09
