### ISSUE TITLE
cannot get tag page to work

### ISSUE THREAD

**Issue by john-qin** [vjeantet/hugo-theme-casper#3]
I am getting 404 page not found when I go to a tag page.

http://localhost:1313/tags/golang/

what do I need to check?

**Comment by john-qin** [comment]
never mind. fix it. need to add tag in config file.

**Comment by vjeantet** [comment]
Hello John, Which config file was you talking about ?
on my side, i only set tags on content .md files like  https://raw.githubusercontent.com/vjeantet/vjeantet.fr/master/content/post/devoxx-france-2014-review.md
