### ISSUE TITLE
Add og:image to header file

### ISSUE THREAD

**Issue by ksred** [vjeantet/hugo-theme-casper#33]
Currently when posts, pages and the home page are shared to social media, the image pulled as the featured image is the first image found on the page. This image should be the cover image/featured image for the post.

Fix: Add the following lines to layouts/partials/header.html

```
{{if .Params.image }}
   <meta property="og:image" content="{{ .Site.BaseURL }}{{.Params.image}}"/>
{{else}}
    {{if .Site.Params.cover}}
        <meta property="og:image" content="{{ .Site.BaseURL }}{{.Site.Params.cover}}"/>
    {{end}}
{{end}}
```

**Comment by anthonylavado** [comment]
@ksred, I've added this in as part of #68. Let me know if it works for you before we ask Valere to merge.

**Comment by ksred** [comment]
@anthonylavado Awesome, looks great! Apologies for not getting around to this earlier, thanks for doing the PR.

**Comment by anthonylavado** [comment]
@vjeantet Is it possible to get this in?

**Comment by vjeantet** [comment]
Yes ! you PR this ! Thanks
