### ISSUE TITLE
How can I show the article digest instead of all text in main page?

### ISSUE THREAD

**Issue by longkai** [vjeantet/hugo-theme-casper#34]
I am new to hugo.

I follow the sample and run my own site, however I could not see the message digest in the main page instead of all text.

How should I do? Thx in advance.

**Comment by baldore** [comment]
Do you mean like the summary of the content?

**Comment by longkai** [comment]
Yes.

**Comment by baldore** [comment]
Take a look at this: https://gohugo.io/content/summaries/

**Comment by longkai** [comment]
Thank you.

I have read it and I suppose it has something to do with the character. In Chinese a word has length 2 may have 8(or more) length after translating to English word.

So, Could you tell me how can I set limit to the summary of the content. Thank you in advance.

**Comment by dahoba** [comment]
I think you should use manual summary, `<!--more-->`. Without worry about the length of the characters (which is used by automatic summary)

**Comment by vjeantet** [comment]
Hello @longkai, did the @dahoba's solution fixed your issue ?

**Comment by wshito** [comment]
In `config.toml`, set as follows.
````
hasCJKLanguage = true
````

See https://gohugo.io/content-management/summaries/

> The Hugo-defined summaries are set to use word count calculated by splitting the text by one or more consecutive white space characters. If you are creating content in a CJK language and want to use Hugo’s automatic summary splitting, set hasCJKLanguage to true in you site configuration.

**Comment by vjeantet** [comment]
Thanks @wshito
