### ISSUE TITLE
footer partial does not render html entites

### ISSUE THREAD

**Issue by derektamsen** [vjeantet/hugo-theme-casper#39]
The footer partial does not support rendering [HTML Entities] (http://www.w3schools.com/html/html_entities.asp). When the site `config` file contains the following:

    Copyright = "&copy; Example, Inc."

The rendered result contains the literal "\&copy; Example, inc." text.

The rendered output for the footer partial should contain "&copy; Example, inc.".

**Comment by vjeantet** [comment]
PR merged thanks
