### ISSUE TITLE
Unexpected cover image behavior

### ISSUE THREAD

**Issue by jmMeessen** [vjeantet/hugo-theme-casper#54]
I have difficulties managing the cover image and could use some guidance.

When I specify an image in cover, under [params] in the config.toml, I don't get the same result as on the demo site (http://vjeantet.fr/). On the demo site, the image is shown "full" screen while on my test site, the picture is shown as all width of the screen but about 25% of the hight. I tried with the same picture as on the demo site (cover_polenord).

I have no clue how to get the cover effect of the demo.

Jmm

**Comment by jmMeessen** [comment]
To help narrowing down, I observed that my `index.html` is generated with the following line:
````
<header class="main-header tag-head" style="background-image: url(http://localhost/images/cover_polenord.jpg)">
````
When I remove the `tag-head` in the class name, I get the desired behavior.

What am I doing wrong ?

Jmm

**Comment by anthonylavado** [comment]
Looks like this is an issue that has an Open PR:
https://github.com/vjeantet/hugo-theme-casper/pull/49

I've corrected it manually (as you have) in index.html for the time being.

**Comment by jmMeessen** [comment]
Thank you very much for that workaround, Anthony.

**Comment by anthonylavado** [comment]
And it looks like @vjeantet has merged it, so we should be good from here on out!
I'll take a look at it tonight, but @jmMeessen if it works for you, we might be good to close this.

**Comment by jmMeessen** [comment]
I just made the necessary "git subrepo" voodoo and can confirm that the latest version of the theme now works.

So I can close this issue.

**Comment by vjeantet** [comment]
Thanks for reporting and for the PR !
