### ISSUE TITLE
Feature: "read more" suggestions at the end

### ISSUE THREAD

**Issue by sungwoncho** [vjeantet/hugo-theme-casper#60]
Possible feature: suggest other articles at the end of an article.

Casper for Ghost does this well.

**Comment by arthur-flam** [comment]
Hi,
First of all thanks for the great work porting the casper theme to hugo.
I reworked this theme slightly last week to support "readnexts":
Sorry I don't have enough time in the short term to make a proper pull request.
Here are the changes:

1. New partial *readnext.html*
``` html
<!-- needs to be improved: fails for first/last articles -->
{{ $next := or .NextInSection .Next . }}
{{ $prev := or .PrevInSection .Prev . }}

<aside class="read-next">
{{with $next}}
<a class="read-next-story next " style="background-image: url(/{{or .Params.cover .Site.Params.cover}})" href="{{ .Permalink }}">
  <section class="post">
    <h2>{{.Title}}</h2>
    <p>{{.Description}}</p>
  </section>
</a>
{{end}}
{{with $prev}}
<a class="read-next-story prev " style="background-image: url(/{{or .Params.cover .Site.Params.cover}})" href="{{ .Permalink }}">
  <section class="post">
    <h2>{{.Title}}</h2>
    <p>{{.Description}}</p>
  </section>
</a>
{{end}}
</aside>
```

2. At the end of *_default/single.html* I added before the footer:
```html
{{ partial "readnext.html" . }}
```

3. I picked the current [casper css](https://github.com/TryGhost/Casper/blob/master/assets/css/screen.css), modified to use this theme's icon font.


Best,
Arthur

**Comment by vjeantet** [comment]
Thanks ! I'll implement this

**Comment by sungwoncho** [comment]
I implemented something similar to @arthur-flam's suggestion in on my blog. Happy to do a PR.

**Comment by anthonylavado** [comment]
@sungwoncho Just going through this now - how should this be implemented/turned on? We may want to suggest an update to the readme for this.

**Comment by sungwoncho** [comment]
@anthonylavado The feature is turned on automatically. If I remember correctly, the implementation is as follows:

* if inside a post page, the twitter card will use the post title, summary, and photo
* if outside, it will use the site title, summary, and photo.

I agree that a doc might be helpful.

**Comment by anthonylavado** [comment]
@sungwoncho Oh, I was referring to the suggestions. At any rate though, I wonder about updating the README.

@vjeantet, I can try to create a draft including this if you would like?

**Comment by anthonylavado** [comment]
@sungwoncho I figured out what's happening. The changes you've made are in the `/layouts/page` directory, but there are also template pages in the `/layouts/_default/` directory.

The _default page takes precedence, and it doesn't have the include for the suggestions at the bottom.
