### ISSUE TITLE
Can't hide share buttons on "About me" page

### ISSUE THREAD

**Issue by FilipMiletic** [vjeantet/hugo-theme-casper#62]
Despite setting `noauthor = true share = false` share buttons are still there, and things look somewhat broken. Here is the screenshot:

<img width="1363" alt="screen shot 2016-09-05 at 14 49 56" src="https://cloud.githubusercontent.com/assets/10340299/18248387/14368e26-7378-11e6-8cbb-4b2f85558a0d.png">

Did I config something wrong in parameters for about.md, even though I think thing is pretty straightforward .

**Comment by vjeantet** [comment]
Hello, i can not reproduce this issue, please reopen it if you still have this issue
