### ISSUE TITLE
Pagination by month, not by count of articles?

### ISSUE THREAD

**Issue by vielmetti** [vjeantet/hugo-theme-casper#63]
I have ported in a number of articles from an old, old weblog and now I have 80+ pages of pagination. Needless to say this isn't an ideal setup.

One thing I've done in previous blogs is have some kind of pagination by month or year. Is it possible in Casper to do this?

**Comment by vjeantet** [comment]
yes it could.

If you still need this, are you ok to PR this feature ?

**Comment by vielmetti** [comment]
I don't need this now (as I have paused blogging for a while)
