### ISSUE TITLE
cover image on post's and page's

### ISSUE THREAD

**Issue by BlackbeardEC** [vjeantet/hugo-theme-casper#64]
Not really an issue more of a question. But I'm having a hard time figuring out how to display the 'cover' image that is on main page on the individual post's and page's. 

The cover displays on 'tag' pages, and I want to display the cover image like it is on the tag pages (kind of shortened with the 'tag' overlaying the shortened image) on the post/page page's with the post/page title overlaying the image.

Thanks for your input and thanks for the theme.

**Comment by vjeantet** [comment]
Hello, just use the same image path in page `image` param
```
image = "images/cover_polenord.jpg"
```
