### ISSUE TITLE
Displaying author for multiple author

### ISSUE THREAD

**Issue by sungwoncho** [vjeantet/hugo-theme-casper#71]
I have a problem with displaying author info in the post index when using multiple author.

I have correctly placed yaml file to configure an author as per README.

But the [current code](https://github.com/vjeantet/hugo-theme-casper/blob/c7c8d72881318f7df278cc0dc56255db1c773318/layouts/partials/li.html#L10-L16) for displaying the author did not work.

I replaced the highlighted code with the following, and now the author is displaying correctly.

    {{$author := or (index .Site.Data.authors .Params.author) .Site.Params.author }}

The issue is that `$author` is `.Site.Params.author` even when the multiple author is configured.

I have confirmed that the [innermost conditional](https://github.com/vjeantet/hugo-theme-casper/blob/c7c8d72881318f7df278cc0dc56255db1c773318/layouts/partials/li.html#L14) is being reached. But still, `$author` defined on [line 10](https://github.com/vjeantet/hugo-theme-casper/blob/c7c8d72881318f7df278cc0dc56255db1c773318/layouts/partials/li.html#L10) is not being overwritten.

Any ideas?

**Comment by vjeantet** [comment]
fixed in https://github.com/vjeantet/hugo-theme-casper/commit/dc282fe297f2e93b86fcbaf298c49dc0b253dcfd
