### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by enfrte** [vjeantet/hugo-theme-casper#76]
Hi, I'm new to go and don't really understand this error message. Is it related to the Casper theme or the Hugo framework?
```
$ hugo --theme=casper
Started building sites ...
ERROR: 2017/02/19 11:12:48 general.go:236: theme/partials/semantic.html is an incomplete or empty template
Built site for language en:
0 draft content
0 future content
0 expired content
2 regular pages created
2 other pages created
0 non-page files copied
2 paginator pages created
0 tags created
0 categories created
total in 167 ms
```
Thanks.

**Comment by vjeantet** [comment]
Thanks I will check that

**Comment by ts1829** [comment]
Also got a build error.

```'bash
ERROR: 2017/04/01 16:11:46 template.go:350: template: theme/partials/semantic.html:25: function "slice" not defined
ERROR: 2017/04/01 16:11:46 template.go:119: html/template: "theme/partials/semantic.html" is an incomplete template in theme/partials/semantic.html
panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value
```

**Comment by hieverest** [comment]
Hi, I am very new to Hugo and I love your theme. But have many errors when I try to build the sites.
My Hugo version is 0.20.2  windows/amd64

Started building sites ...
ERROR 2017/04/19 09:58:51 Error while rendering "home": template: theme/index.html:1:3: executing "theme/index.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:8:7: executing "theme/partials/header.html" at <partial "twitter_car...>: error calling partial: template: theme/partials/twitter_card.html:11:64: executing "theme/partials/twitter_card.html" at <relURL>: wrong number of args for relURL: want 1 got 0

ERROR 2017/04/19 09:58:51 Error while rendering "section": template: theme/_default/list.html:1:3: executing "theme/_default/list.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:8:7: executing "theme/partials/header.html" at <partial "twitter_car...>: error calling partial: template: theme/partials/twitter_card.html:11:64: executing "theme/partials/twitter_card.html" at <relURL>: wrong number of args for relURL: want 1 got 0

ERROR 2017/04/19 09:58:51 Error while rendering "page": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:101:5: executing "theme/partials/header.html" at <partial "navigation....>: error calling partial: template: theme/partials/navigation.html:9:17: executing "theme/partials/navigation.html" at <sort .Site.Menus.mai...>: error calling sort: sequence must be provided

ERROR 2017/04/19 09:58:51 Error while rendering "page": template: theme/page/single.html:1:3: executing "theme/page/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:101:5: executing "theme/partials/header.html" at <partial "navigation....>: error calling partial: template: theme/partials/navigation.html:9:17: executing "theme/partials/navigation.html" at <sort .Site.Menus.mai...>: error calling sort: sequence must be provided

ERROR 2017/04/19 09:58:51 Error while rendering "404": template: theme/404.html:1:3: executing "theme/404.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:8:7: executing "theme/partials/header.html" at <partial "twitter_car...>: error calling partial: template: theme/partials/twitter_card.html:11:64: executing "theme/partials/twitter_card.html" at <relURL>: wrong number of args for relURL: want 1 got 0

**Comment by 4sStylZ** [comment]
Hi,

I think I have a similar problem too : 

```
4s@StylZ:~/Documents/Projects/4sStylZ-blog$ hugo version
Hugo Static Site Generator v0.20.2 linux/amd64 BuildDate: 2017-04-16T13:21:30+02:00

4s@StylZ:~/Documents/Projects/4sStylZ-blog$ hugo server --theme=casper --buildDraftsStarted building sites ...
ERROR 2017/04/21 15:30:10 Error while rendering "home": template: theme/index.html:1:3: executing "theme/index.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:8:7: executing "theme/partials/header.html" at <partial "twitter_car...>: error calling partial: template: theme/partials/twitter_card.html:11:64: executing "theme/partials/twitter_card.html" at <relURL>: wrong number of args for relURL: want 1 got 0
ERROR 2017/04/21 15:30:10 Error while rendering "page": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:101:5: executing "theme/partials/header.html" at <partial "navigation....>: error calling partial: template: theme/partials/navigation.html:9:17: executing "theme/partials/navigation.html" at <sort .Site.Menus.mai...>: error calling sort: sequence must be provided
ERROR 2017/04/21 15:30:10 Error while rendering "section": template: theme/_default/list.html:1:3: executing "theme/_default/list.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:8:7: executing "theme/partials/header.html" at <partial "twitter_car...>: error calling partial: template: theme/partials/twitter_card.html:11:64: executing "theme/partials/twitter_card.html" at <relURL>: wrong number of args for relURL: want 1 got 0
ERROR 2017/04/21 15:30:10 Error while rendering "404": template: theme/404.html:1:3: executing "theme/404.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:8:7: executing "theme/partials/header.html" at <partial "twitter_car...>: error calling partial: template: theme/partials/twitter_card.html:11:64: executing "theme/partials/twitter_card.html" at <relURL>: wrong number of args for relURL: want 1 got 0
Built site for language en:
1 of 1 draft rendered
0 future content
0 expired content
1 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 5 ms
Watching for changes in /home/aschmitt/Documents/Projects/4sStylZ-blog/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

New to Hugo too. Sorry if this is a stupid question.

**Comment by vjeantet** [comment]
Hello I'll have a look. Can you provide me the content you are trying to generate ?

**Comment by vjeantet** [comment]
I can not reproduce this issue, can you send me your content and config.toml ?

**Comment by asimumba** [comment]
I had the same problem with the config.toml file that is downloaded by default. All I did to work around it was I copied the example config file values in the readme file.
