### ISSUE TITLE
Posts in the root directory

### ISSUE THREAD

**Issue by kirtan403** [vjeantet/hugo-theme-casper#77]
My current ghost blog has urls at the root. Like `www.mysite.com/post-slug`. But this theme assumes that all the posts are under `/post/post-slug`. I want the same url structure as per my current blog structure.

How can I achieve this with this theme? Which files needs modifications? Can someone provide some guidance.

Thank you so much.

**Comment by kirtan403** [comment]
I have done with the help of parmalinks.

**Comment by vjeantet** [comment]
👍
