### ISSUE TITLE
What is customHeaderPartial in the header.html ?

### ISSUE THREAD

**Issue by kirtan403** [vjeantet/hugo-theme-casper#79]
I see a line at the end of the <head> section in the header.html file.

    {{ if .Site.Params.customHeaderPartial }}
        {{ partial .Site.Params.customHeaderPartial . }}
    {{ end }}

There isn't anything documented about this. Can someone provide some detail on this?

**Comment by vjeantet** [comment]
Hello @kirtan403 

it allows you to customize headers.html without touching it.. .

Have a look here :
https://github.com/vjeantet/hugo-theme-casper/commit/ca2b8c2383b33f92f416efd66bc497d03061285f
