### ISSUE TITLE
Changes for Hugo 0.20

### ISSUE THREAD

**Issue by vielmetti** [vjeantet/hugo-theme-casper#84]
Hugo 0.20 has several changes, which can break Casper sites, or that can make them better.

One theme suggestion comes from

https://discuss.gohugo.io/t/hugo-0-20-upgrade-page-template-breaks/6097

which suggests a fix to layouts/partials/header.html to use relURL instead of concatenation in generating new URLs.

This is connected to https://github.com/spf13/hugo/issues/3262

**Comment by vjeantet** [comment]
Hello, i'm on it
