### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by nlimpid** [vjeantet/hugo-theme-casper#87]
I copy the entire config and Metadata in the readme, but hugo build error, the msg is as blow.

```
ERROR: 2017/05/14 11:03:43 template.go:131: 
template: theme/partials/semantic.html:39:31: 
executing "theme/partials/semantic.html" at <.Site.Language.Lang>: 
can't evaluate field Language in type *hugolib.SiteInfo in theme/partials/semantic.html
```

I check the error place, the code seems that I miss the param in the config. I try something param  still not work.

```
  "alternateName": {{ .Site.Language.Lang }}
```

Finally I delete this line, then build error disapear.

**Comment by vjeantet** [comment]
can not reproduce on hugo 0.25, if you still have the issue, reopen this ticket
