### ISSUE TITLE
.RSSLink is blank on single pages

### ISSUE THREAD

**Issue by bep** [vjeantet/hugo-theme-casper#9]
.RSSLink makes sense on Nodes, but is empty on pages. Maybe add a conditional that returns the site RSS when on a single page?

**Comment by vjeantet** [comment]
Hello @bep , ok with this.

I'm looking for the appropriate variable to print the site RSS, i can not find it.. :(

http://gohugo.io/templates/variables/

Maybe i have to "hardcode" the site RSS link ?

**Comment by bep** [comment]
Yes, I do not think there is a .Site.RSSLink (it should be ...). But it's a static value, so hardcode is OK.
