### ISSUE TITLE
Twitter card should include cover image when present

### ISSUE THREAD

**Issue by jramnani** [vjeantet/hugo-theme-casper#97]
PR #96 introduced a bug where the site build would throw errors when a cover image was specified.

The cause of the bug was that I had misunderstood what the `with` expression does in Hugo templates.  I thought it was a simple null check, but it also changes the current context (the dot `.`), as well.

My apologies for the error.  A PR is coming shortly that fixes this issue.

**Comment by jramnani** [comment]
PR with fix in #98 .

**Comment by vjeantet** [comment]
done, thanks @jramnani
